---
- name: Set up k3s master node
  hosts: all
  become: True
  vars:
    k3s_skip_validation: true
    k3s_control_node_address: loadbalancer  # Typically a load balancer.
    k3s_server:
      datastore-endpoint: "postgresql://{{ database_user}}:{{ database_password}}@{{ database_host }}/{{ database_name }}"
  pre_tasks:
    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: inventory_hostname in ['k3s_master']
  roles:
    - role: 'xanmanning.k3s'
